project_name: saml2alibabacloud
release:
  github:
    owner: aliyun
    name: saml2alibabacloud

builds:
  - id: saml2alibabacloud_darwin
    main: ./cmd/saml2alibabacloud/main.go
    binary: saml2alibabacloud
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.Version={{.Version}}
  - id: saml2alibabacloud_windows
    main: ./cmd/saml2alibabacloud/main.go
    binary: saml2alibabacloud
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
  - id: saml2alibabacloud_linux
    main: ./cmd/saml2alibabacloud/main.go
    binary: saml2alibabacloud
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: default
    ids:
      - saml2alibabacloud_darwin
      - saml2alibabacloud_linux
    formats: 
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE.md
    wrap_in_directory: false

  - id: windows
    ids:
      - saml2alibabacloud_windows
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE.md
    wrap_in_directory: false

checksum:
  name_template: "checksums.txt"

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:' 